load("@aspect_rules_js//js:defs.bzl", "js_binary")

package(default_visibility = ["//visibility:public"])

js_binary(
    name = "post_process",
    entry_point = ":post_process.js",
    visibility = ["//visibility:public"],
)
